name    'openstack-hyper-v-windows_git'
version '0.1.0'
source 'https://github.com/openstack-hyper-v/puppet-windows_git.git'
author 'Peter Pouliot <peter@pouliot.net>'
license 'Apache License, Version 2.0'
summary 'Puppet module for installing git on the Windows Platform'
description 'Puppet module for installing git on the Windows Platform'
project_page 'https://github.com/openstack-hyper-v/puppet-windows_git'
dependency 'joshcooper/powershell'
dependency 'openstack-hyper-v/windows_common'
dependency 'basti1302/windows_path'
dependency 'chocolatey/chocolatey'
